#!/usr/bin/perl

my $Debug = $ENV{'LOGWATCH_DEBUG'};
my $Detail = $ENV{'LOGWATCH_DETAIL_LEVEL'};
my $Error = 0;
my @ErrorLines = ();


while (defined($ThisLine = <STDIN>)) {
    if ( $ThisLine =~ /started/ ){
        print $ThisLine;
    }
    if ( $ThisLine =~ /completed successfully/ ) {
        print $ThisLine;
    }
    if ($ThisLine =~ /ERROR: /) {
        @ErrorLines[$Error] = $ThisLine;
        $Error++;
    }
}


if ($Error == 1) {
    print "$Error rsnapshot error:\n";
}

if ($Error > 1) {
    print "$Error rsnapshot errors:\n";
}

if (($Detail >= 0) and (scalar(@ErrorLines) > 0)) {
    for ($count = 0; $count <= scalar(@ErrorLines); $count++) {
        print "@ErrorLines[$count]";
    }
}

exit(0);
